Fix cwd path for runCommands on windows
Sometime we were getting
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Administrateur\source\repos\accendino\_v\Scripts\accendino.exe\__main__.py", line 7, in <module>
    sys.exit(main())
             ~~~~^^
  File "C:\Users\Administrateur\source\repos\accendino\_v\Lib\site-packages\accendino\main.py", line 620, in main
    return run(sys.argv)
  File "C:\Users\Administrateur\source\repos\accendino\_v\Lib\site-packages\accendino\main.py", line 612, in run
    if not buildModule(item):
           ~~~~~~~~~~~^^^^^^
  File "C:\Users\Administrateur\source\repos\accendino\_v\Lib\site-packages\accendino\main.py", line 591, in buildModule
    if not buildItem.build(config):
           ~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\Administrateur\source\repos\accendino\_v\Lib\site-packages\accendino\builditems.py", line 360, in build
    return self.runCommands(self.build_cmds, env, config) and self.createBuiltFile()
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrateur\source\repos\accendino\_v\Lib\site-packages\accendino\builditems.py", line 241, in runCommands
    completedProc = subprocess.run(cmd, env=env, cwd=path, stdout=flog, stderr=flog)
  File "C:\Program Files\Python313\Lib\subprocess.py", line 554, in run
    with Popen(*popenargs, **kwargs) as process:
         ~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\subprocess.py", line 1036, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        pass_fds, cwd, env,
                        ^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
                        gid, gids, uid, umask,
                        ^^^^^^^^^^^^^^^^^^^^^^
                        start_new_session, process_group)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\subprocess.py", line 1548, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
                             # no special security
                             ^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
                             cwd,
                             ^^^^
                             startupinfo)
                             ^^^^^^^^^^^^
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable
```

When running the commands because of an invalid running directory